FROM openjdk:11
MAINTAINER Yash Yadav<yash.mlvt@gmail.com>
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/online-shopping-0.0.2-SNAPSHOT.war
ADD ${JAR_FILE} online-shopping-0.0.2-SNAPSHOT.war
ENTRYPOINT ["java","-jar","/online-shopping-0.0.2-SNAPSHOT.war"]
